export const SITE_CONFIG = {
  name: 'Web Audits Helper',
  legacyName: 'VitalsSniper PRO',
  tagline: 'Web Tools. Reviewed. Ranked. Trusted.',
  domain: 'webaudits.pro',
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || 'https://webaudits.pro',
  supportEmail: 'support@webaudits.pro',
  description: 'Your trusted guide to web performance tools, hosting, and site speed - plus our flagship VitalsSniper PRO inspector.',
  appsumoUrl: process.env.NEXT_PUBLIC_APPSUMO_URL || '/vitalssniper#auditor',
  docsUrl: '/docs',
  licenseUrl: '/license',
  dashboardUrl: '/dashboard',
  pricingUrl: '/pricing',
  vitalsniperUrl: '/vitalssniper',
  toolsUrl: '/tools',
  blogUrl: '/blog',
  categories: [
    'Speed & Performance',
    'Hosting & CDN',
    'Page Builders',
    'SEO Tools',
    'Analytics',
    'Security',
  ] as const,
  pricing: {
    free: {
      price: 0,
      period: 'forever',
      audits: '1 scan / week',
      seats: 1,
    },
    pro: {
      price: 49,
      period: 'mo',
      appsumoPrice: 39,
      audits: 'Unlimited (client-side)',
      seats: 5,
    },
    enterprise: {
      price: 399,
      period: 'mo',
      audits: 'Unlimited + API access',
      seats: 25,
    },
  },
};
